# Generated by Django 3.0.7 on 2020-06-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200617_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='ip',
            field=models.CharField(default='', max_length=16, verbose_name='IP анонимного клиента'),
        ),
        migrations.AddField(
            model_name='favorites',
            name='ip',
            field=models.CharField(default='', max_length=16, verbose_name='IP анонимного клиента'),
        ),
    ]
