# Generated by Django 3.0.7 on 2020-06-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200618_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Колличество'),
        ),
        migrations.AddField(
            model_name='favorites',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Колличество'),
        ),
    ]
